CREATE DATABASE ABCBANK;


CREATE TABLE USER_TRANSACTION (
  USER_ROLE_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(45) NOT NULL,
  FIRST_NAME VARCHAR(45) NOT NULL,
  LAST_NAME VARCHAR(45) NOT NULL,
  PAYEE_NAME VARCHAR(45) NOT NULL,
  TRANSFER_AMT VARCHAR(45) NOT NULL,
  USER_ACCOUNT_NO VARCHAR(45) NOT NULL,
   TRANSCT_DATE DATE,
  PRIMARY KEY (USER_ROLE_ID)

  );
  
-- DROP TABLE USER_TRANSACTION;

  SELECT * FROM USER_TRANSACTION ;
  
  SELECT * FROM USER_TRANSACTION WHERE USER_NAME = "channaveerpatil";
 

INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "JOHN", "400", "4455667788", "2018-01-22");
INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "Stveh", "200", "4455667788", "2018-02-22");
INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "Carl", "400", "4455667788", "2018-03-22");
INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "Smith", "400", "4455667788", "2018-04-22");
INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "smith", "300", "4455667788", "2018-05-22");
INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "Smith", "800", "4455667788", "2018-06-22");
INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "John", "700", "4455667788", "2018-07-22");
INSERT INTO USER_TRANSACTION (USER_NAME, FIRST_NAME, LAST_NAME, PAYEE_NAME, TRANSFER_AMT, USER_ACCOUNT_NO, TRANSCT_DATE) VALUES ( "channaveerpatil", "Channaveer", "Patil", "John", "600", "4455667788", "2018-08-22");

SELECT SUM(TRANSFER_AMT) AS AMOUNT, TRANSCT_DATE FROM USER_TRANSACTION GROUP BY MONTH(TRANSCT_DATE)
